/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoopRouteImport } from './routes/coop'
import { Route as FarmerRouteImport } from './routes/farmer'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as VetRouteImport } from './routes/vet'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoopRoute = CoopRouteImport.update({
  id: '/coop',
  path: '/coop',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerRoute = FarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const VetRoute = VetRouteImport.update({
  id: '/vet',
  path: '/vet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coop': typeof CoopRoute
  '/farmer': typeof FarmerRoute
  '/onboarding': typeof OnboardingRoute
  '/vet': typeof VetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coop': typeof CoopRoute
  '/farmer': typeof FarmerRoute
  '/onboarding': typeof OnboardingRoute
  '/vet': typeof VetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coop': typeof CoopRoute
  '/farmer': typeof FarmerRoute
  '/onboarding': typeof OnboardingRoute
  '/vet': typeof VetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/coop' | '/farmer' | '/onboarding' | '/vet'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/coop' | '/farmer' | '/onboarding' | '/vet'
  id: '__root__' | '/' | '/coop' | '/farmer' | '/onboarding' | '/vet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoopRoute: typeof CoopRoute
  FarmerRoute: typeof FarmerRoute
  OnboardingRoute: typeof OnboardingRoute
  VetRoute: typeof VetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coop': {
      id: '/coop'
      path: '/coop'
      fullPath: '/coop'
      preLoaderRoute: typeof CoopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer': {
      id: '/farmer'
      path: '/farmer'
      fullPath: '/farmer'
      preLoaderRoute: typeof FarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet': {
      id: '/vet'
      path: '/vet'
      fullPath: '/vet'
      preLoaderRoute: typeof VetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoopRoute: CoopRoute,
  FarmerRoute: FarmerRoute,
  OnboardingRoute: OnboardingRoute,
  VetRoute: VetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
