/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoopRouteImport } from './routes/coop'
import { Route as FarmerRouteImport } from './routes/farmer'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as VetRouteImport } from './routes/vet'
import { Route as FarmerIndexRouteImport } from './routes/farmer.index'
import { Route as FarmerAlertsRouteImport } from './routes/farmer.alerts'
import { Route as FarmerHerdRouteImport } from './routes/farmer.herd'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoopRoute = CoopRouteImport.update({
  id: '/coop',
  path: '/coop',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerRoute = FarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const VetRoute = VetRouteImport.update({
  id: '/vet',
  path: '/vet',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerIndexRoute = FarmerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerAlertsRoute = FarmerAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerHerdRoute = FarmerHerdRouteImport.update({
  id: '/herd',
  path: '/herd',
  getParentRoute: () => FarmerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coop': typeof CoopRoute
  '/farmer': typeof FarmerRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/vet': typeof VetRoute
  '/farmer/alerts': typeof FarmerAlertsRoute
  '/farmer/herd': typeof FarmerHerdRoute
  '/farmer/': typeof FarmerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coop': typeof CoopRoute
  '/onboarding': typeof OnboardingRoute
  '/vet': typeof VetRoute
  '/farmer/alerts': typeof FarmerAlertsRoute
  '/farmer/herd': typeof FarmerHerdRoute
  '/farmer': typeof FarmerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coop': typeof CoopRoute
  '/farmer': typeof FarmerRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/vet': typeof VetRoute
  '/farmer/alerts': typeof FarmerAlertsRoute
  '/farmer/herd': typeof FarmerHerdRoute
  '/farmer/': typeof FarmerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coop'
    | '/farmer'
    | '/onboarding'
    | '/vet'
    | '/farmer/alerts'
    | '/farmer/herd'
    | '/farmer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coop'
    | '/onboarding'
    | '/vet'
    | '/farmer/alerts'
    | '/farmer/herd'
    | '/farmer'
  id:
    | '__root__'
    | '/'
    | '/coop'
    | '/farmer'
    | '/onboarding'
    | '/vet'
    | '/farmer/alerts'
    | '/farmer/herd'
    | '/farmer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoopRoute: typeof CoopRoute
  FarmerRoute: typeof FarmerRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  VetRoute: typeof VetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coop': {
      id: '/coop'
      path: '/coop'
      fullPath: '/coop'
      preLoaderRoute: typeof CoopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer': {
      id: '/farmer'
      path: '/farmer'
      fullPath: '/farmer'
      preLoaderRoute: typeof FarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet': {
      id: '/vet'
      path: '/vet'
      fullPath: '/vet'
      preLoaderRoute: typeof VetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/': {
      id: '/farmer/'
      path: '/'
      fullPath: '/farmer/'
      preLoaderRoute: typeof FarmerIndexRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/alerts': {
      id: '/farmer/alerts'
      path: '/alerts'
      fullPath: '/farmer/alerts'
      preLoaderRoute: typeof FarmerAlertsRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/herd': {
      id: '/farmer/herd'
      path: '/herd'
      fullPath: '/farmer/herd'
      preLoaderRoute: typeof FarmerHerdRouteImport
      parentRoute: typeof FarmerRoute
    }
  }
}

interface FarmerRouteChildren {
  FarmerAlertsRoute: typeof FarmerAlertsRoute
  FarmerHerdRoute: typeof FarmerHerdRoute
  FarmerIndexRoute: typeof FarmerIndexRoute
}

const FarmerRouteChildren: FarmerRouteChildren = {
  FarmerAlertsRoute: FarmerAlertsRoute,
  FarmerHerdRoute: FarmerHerdRoute,
  FarmerIndexRoute: FarmerIndexRoute,
}

const FarmerRouteWithChildren =
  FarmerRoute._addFileChildren(FarmerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoopRoute: CoopRoute,
  FarmerRoute: FarmerRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  VetRoute: VetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
